name: Unit Tests

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            SOME_ENV_VAR: "val"

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python 3.8.*
                uses: actions/setup-python@v1
                with:
                    python-version: 3.8.*

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install -r requirements_dev.txt
                    pip install -u tox

            -   name: Build and Test
                run: |
                    tox
