name: WF

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            SOME_ENV_VAR: "val"

        strategy:
            max-parallel: 3
            matrix:
                python-version: [3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt

            - name: Build and Test
              run: |
                  pytest

    publish:
        runs-on: ubuntu-latest
        needs: [test]

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Python 3.8.*
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8.*

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt
                  pip install python_semantic_release

            - name: Python Semantic Release
              uses: relekang/python-semantic-release@master
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  pypi_token: ${{ secrets.PYPI_TOKEN }}
