name: WF

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            SOME_ENV_VAR: "val"

        strategy:
            max-parallel: 3
            matrix:
                python-version: [3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt

            - name: Build and Test
              run: |
                  pytest

    semver:
        runs-on: ubuntu-latest
        needs: test

        env:
            SOME_ENV_VAR: "val"

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.8.*
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8.*

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt
                  pip install python_semantic_release

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt
                  pip install python_semantic_release

            - name: List Semantic Release Information
              run: |
                  semantic-release version
                  semantic-release changelog

    publish:
        runs-on: ubuntu-latest
        needs: [test, semver]

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Python 3.8.*
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8.*

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt
                  pip install python_semantic_release

            - name: Semantic Release Publish
              run: |
                  semantic-release version
                  semantic-release changelog
                  semantic-release publish -v INFO
