name: CI
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            SOME_ENV_VAR: "val"

        strategy:
            max-parallel: 3
            matrix:
                python-version: [3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt

            - name: Build and Test
              run: |
                  pytest

    publish:
        runs-on: ubuntu-latest
        needs: [test]
        if: github.ref == 'refs/heads/master'

        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: 'refs/heads/master'
                  fetch-depth: 0

            - name: Set up Python 3.8.*
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8.*

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt
                  pip install python_semantic_release

            - name: Configure Git
              run: |
                  git config --global user.name "actions-user"
                  git config --global user.email "actions@github.com"

            - name: Semantic Release Publish
              run: |
                  semantic-release publish -v DEBUG
